run: 
	python3 main.py

showHeatmap:
	python3 main.py --show_heatmap	

optimal:
	python3 main.py --find_optimal_features --find_algorithm 

install:
	pip3 install numpy pandas seaborn dash selenium scikit-learn
	